### ISSUE TITLE
Request update support for React 18

### ISSUE THREAD

**Issue by codyslex1a** [robertLichtnow/zod-formik-adapter#11]
**Is your feature request related to a problem? Please describe.**
My console when I install `zod-formik-adapter` 
<img width="603" alt="CleanShot 2022-07-16 at 11 12 46@2x" src="https://user-images.githubusercontent.com/8092790/179338825-0819fe1d-9298-4c86-99d1-3abe8ed64a67.png">

**Comment by oliverjohns** [comment]
Upgrade to React 18 would be awesome!

**Comment by oliverjohns** [comment]
#13 @robertLichtnow Could you approve this PR? :)

**Comment by stefanullinger** [comment]
Hey, I also need this fix in order to install this module properly. Any chance PR #13 can be reviewed and merged? Thanks in advance!

**Comment by jacknewberry** [comment]
I would love this too!

**Comment by stefanullinger** [comment]
Hey, is there any chance we can get this merged?

**Comment by Lukem121** [comment]
You can use:
npm install formik-adapter-zod 

works for React v18

**Comment by robertLichtnow** [comment]
React was removed as a peer dependency, so this should not be a problem anymore.
